apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: quotable
  name: quotable
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: quotable
    spec:
      containers:
      - image: 10.10.40.10:5000/quotable
        name: quotable
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
